export const NODE = 'https://node.tater.ovh';
export const SEED = 'PUEOTSEITFEVEWCWBTSIZM9NKRGJEIMXTULBACGFRQK9IMGICLBKW9TTEVSDQMGWKBXPVCBMMCXWMNPDX'; //Fake seed
export const DEPTH = 3;
export const MINIMUM_WEIGHT_MAGNITUDE = 14;

export const TEST_ADDRESS = 'HEQLOWORLDHELLOWORLDHELLOWORLDHELLOWORLDHELLOWORLDHELLOWORLDHELLOWORLDHELLOWOR99D';
export const DEFAULT_VALUE = '0';

export const TEST_TX_HASH = 'ZPDVUYPPBHRFIMENNBJSWQDTSXDKTAURMUUWATONJT9HDTR9JLOIQG9TQPYBYJ9KPNGMESNUHVIXA9999';
